export const blogs = [
  {
    title: 'Bussin',
    date: '08 Nov 2025',
    blurb: 'All aboaaaaard',
    link: 'bussin',
    img: 'newMap.png',
  },
  {
    title: 'Honk',
    date: '08 Nov 2025',
    blurb: 'Building a very serious Chrome extension',
    link: 'honk',
    img: 'honktml.png',
  },
  {
    title: 'The dream is over',
    date: '22 Oct 2025',
    blurb: 'RIP to my Github contribution streak',
    link: 'streak',
    img: 'contributions.png',
  },
  {
    title: 'Weatherman',
    date: '20 Oct 2025',
    blurb: 'Solving an already solved problem.',
    link: 'weather',
    img: 'weather.png',
  },
  {
    title: 'JSON.parse',
    date: '15 Oct 2025',
    blurb: "Don't trust your console errors",
    link: 'bowling',
    img: 'bowlingError.png',
  },
  {
    title: 'Bloggen V1',
    date: '30 Sep 2025',
    blurb: "Yes, I'm accepting seed money",
    link: 'bloggenv1',
    img: 'bloggenfiles.png',
  },
  {
    title: 'Generation Blog',
    date: '29 Sep 2025',
    blurb: 'How to turn your laziness into productivity',
    link: 'generation-blog',
    img: 'bloggen.png',
  },
  // {
  //   title: 'Foundations Reflections',
  //   date: '23 Sep 2025',
  //   blurb: 'Reflections',
  //   link: 'foundations-reflections',
  // },
  {
    title: 'No Problem.',
    date: '16 Sep 2025',
    blurb: 'Adventures in Slaying Dragons & Squashing Bugs.',
    link: 'problem-solving',
    img: 'jumble.png',
  },
  // {
  //   title: 'Te Whare Tapa Whā.',
  //   date: '15 Sep 2025',
  //   blurb: 'My wellbeing plan.',
  //   link: 'te-whare-tapa-wha',
  //   img: 'te-whare-tapa-wha.png',
  // },
  // {
  //   title: 'Mind, Set, Match',
  //   date: '15 Sep 2025',
  //   blurb: 'Neuroplasticity and Growth Mindset musings.',
  //   link: 'neuroplasticity',
  // },
  {
    title: 'JavaScripting',
    date: '10 Sep 2025',
    blurb: 'An introduction to fundamental JavaScript concepts.',
    link: 'javascript-dom',
    img: 'functionExample.png',
  },
  // {
  //   title: 'Emotional Intelligence',
  //   date: '08 Sep 2025',
  //   blurb: 'What is EQ and how does it differ to IQ?',
  //   link: 'emotional-intelligence',
  // },
  // {
  //   title: 'Learning Plan',
  //   date: '03 Sep 2025',
  //   blurb: 'My plan for success at Dev Academy',
  //   link: 'learning-plan',
  // },
  // {
  //   title: 'Identity & Values',
  //   date: '03 Sep 2025',
  //   blurb: 'A bit about me.',
  //   link: 'identity-values',
  //   img: 'snow.jpg',
  // },
  {
    title: 'CSS Positioning',
    date: '03 Sep 2025',
    blurb: 'Learn about the CSS position property.',
    link: 'html-css',
    img: 'absolute.png',
  },
  // {
  //   title: 'Stories & Legends',
  //   date: '03 Sep 2025',
  //   blurb: 'The Story of Te Houtaewa.',
  //   link: 'te-houtaewa-template',
  // },
]
